{
 "title": "WarehousePG Detailed View",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Cluster", "label": "Cluster", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(warehousepg_observability_loadavg_15min, hostname)"
    }
   },
   {
    "name": "filtered_hostname",
    "label": "filtered_hostname",
    "query": {
     "query": "label_values(warehousepg_observability_du_available_segments{hostname=~\"$hostname\", hostname!~\"coordinator\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Load Average by Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$hostname",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "warehousepg_observability_loadavg_1min{hostname=\"${hostname:raw}\"}",
     "legendFormat": "1 Min % Load"
    },
    {
     "expr": "warehousepg_observability_loadavg_5min{hostname=\"${hostname:raw}\"}",
     "legendFormat": "5 Min % Load"
    },
    {
     "expr": "warehousepg_observability_loadavg_15min{hostname=\"${hostname:raw}\"}",
     "legendFormat": "15 Min % Load"
    }
   ]
  },
  {
   "title": "Disk Usage by Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true
  },
  {
   "title": "Cordinator",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(mountpoint) (warehousepg_observability_du_used_pct_coordinator)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "$filtered_hostname",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "repeat": "filtered_hostname",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "warehousepg_observability_du_used_pct_segments{hostname=\"${filtered_hostname:raw}\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Memory Usage by Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "$hostname",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "warehousepg_observability_mu_memtotal{hostname=\"${hostname:raw}\"} - warehousepg_observability_mu_memfree{hostname=\"${hostname:raw}\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "warehousepg_observability_mu_memfree{hostname=\"${hostname:raw}\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "$hostname",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "warehousepg_observability_mu_memtotal{hostname=\"${hostname:raw}\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "warehousepg_observability_mu_memfree{hostname=\"${hostname:raw}\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "warehousepg_observability_mu_memtotal{hostname=\"${hostname:raw}\"} - warehousepg_observability_mu_memfree{hostname=\"${hostname:raw}\"}",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "Swap Memory Usage by Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "$hostname",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "warehousepg_observability_mu_swaptotal{hostname=\"${hostname:raw}\"} - warehousepg_observability_mu_swapfree{hostname=\"${hostname:raw}\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "warehousepg_observability_mu_swapfree{hostname=\"${hostname:raw}\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "$hostname",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "warehousepg_observability_mu_swaptotal{hostname=\"${hostname:raw}\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "warehousepg_observability_mu_swaptotal{hostname=\"${hostname:raw}\"} - warehousepg_observability_mu_swapfree{hostname=\"${hostname:raw}\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "warehousepg_observability_mu_swapfree{hostname=\"${hostname:raw}\"}",
     "legendFormat": "Free"
    }
   ]
  }
 ]
}