{
 "title": "WarehousePG",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Cluster", "label": "Cluster", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(warehousepg_observability_loadavg_15min, hostname)"
    }
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": {
     "query": "label_values(warehousepg_observability_du_used_pct_segments, mountpoint)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "warehousepg_observability_connected",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "warehousepg_observability_clinfo_primary_count - warehousepg_observability_clinfo_primary_down_count",
     "legendFormat": "Primary Segments Up"
    },
    {
     "expr": "warehousepg_observability_clinfo_primary_down_count",
     "legendFormat": "Primary Segment Down"
    },
    {
     "expr": "warehousepg_observability_clinfo_mirror_count - warehousepg_observability_clinfo_mirror_down_count",
     "legendFormat": "Mirror Segments Up"
    },
    {
     "expr": "warehousepg_observability_clinfo_mirror_down_count",
     "legendFormat": "Mirror Segments Down"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "warehousepg_observability_db_size",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  { "title": "Disk Usage by Mount Points", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Cordinator Disk Usage",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(hostname, mountpoint)(warehousepg_observability_du_used_pct_coordinator)",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "100 - sum(avg by(hostname, mountpoint)(warehousepg_observability_du_used_pct_coordinator))",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "$mountpoint",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "repeat": "mountpoint",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(mountpoint) (warehousepg_observability_du_used_pct_segments{mountpoint=\"$mountpoint\"})",
     "legendFormat": "Avg "
    },
    {
     "expr": "max by(mountpoint) (warehousepg_observability_du_used_pct_segments{mountpoint=\"$mountpoint\"})",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Load Average", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Host Load average ",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (warehousepg_observability_loadavg_1min)",
     "legendFormat": "1 Min % Load"
    },
    {
     "expr": "avg (warehousepg_observability_loadavg_5min)",
     "legendFormat": "5 Min % Load"
    },
    {
     "expr": "avg (warehousepg_observability_loadavg_15min)",
     "legendFormat": "15 Min % Load"
    }
   ]
  },
  { "title": "Host Memory Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory Usage",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(warehousepg_observability_mu_memtotal) - sum(warehousepg_observability_mu_memfree)",
     "legendFormat": "Used"
    },
    {
     "expr": " sum(warehousepg_observability_mu_memfree)",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(warehousepg_observability_mu_swaptotal)- sum(warehousepg_observability_mu_swapfree)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(warehousepg_observability_mu_swapfree)",
     "legendFormat": "Free"
    }
   ]
  },
  { "title": "Query Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "warehousepg_observability_q_active",
     "legendFormat": "Active queries"
    },
    {
     "expr": "warehousepg_observability_q_idle",
     "legendFormat": "Idle queries"
    }
   ]
  },
  {
   "title": "Queries per user",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 31 },
   "targets": [
    { "expr": "warehousepg_observability_qu", "legendFormat": "{{username}}" }
   ]
  },
  { "title": "Log Info (Last 10 Mins) ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "warehousepg_observability_log_10m_panic",
     "legendFormat": "Panic"
    },
    {
     "expr": "warehousepg_observability_log_10m_fatal",
     "legendFormat": "Fatal"
    },
    {
     "expr": "warehousepg_observability_log_10m_error",
     "legendFormat": "Error"
    }
   ]
  }
 ]
}