{
 "title": "WarehousePG-Detailed",
 "tags": [ "whpg" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSourcePrometheus", "label": "DataSourcePrometheus", "query": "prometheus" },
   {
    "name": "DataSourceInfinity",
    "label": "DataSourceInfinity",
    "query": "yesoreyeram-infinity-datasource"
   },
   { "name": "DataSourceLoki", "label": "DataSourceLoki", "query": "loki" },
   {
    "name": "HostMountPoints",
    "label": "HostMountPoints",
    "query": {
     "query": "label_values(warehousepg_observability_node_filesystem_free_bytes,mountpoint)"
    }
   },
   {
    "name": "HostList",
    "label": "HostList",
    "query": {
     "query": "label_values(warehousepg_observability_node_filesystem_free_bytes,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Table Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Object Details",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "parser": "backend",
       "source": "url",
       "type": "json",
       "url": "/object_list",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "Largest Table List",
     "type": "table",
     "description": "This presents list of largest top 20 tables. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "parser": "backend",
       "source": "url",
       "type": "json",
       "url": "/top_N_largest_tables",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "Bloated Table List",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "parser": "backend",
       "source": "url",
       "type": "json",
       "url": "/bloated_table_list",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "Tables with most dead rows",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "parser": "backend",
       "source": "url",
       "type": "json",
       "url": "/table_with_most_dead_rows",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "List of Un-Vacuumed table",
     "type": "table",
     "description": "This presents a list of top 20 un-vacuumed table by order of number of dead tuples.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "parser": "backend",
       "source": "url",
       "type": "json",
       "url": "/top_N_not_vacuumed_tables",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "List of not Analysed tables",
     "type": "table",
     "description": "This shows the top 20 tables ranked by the count of columns with missing optimizer stats",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "parser": "backend",
       "source": "url",
       "type": "json",
       "url": "/top_N_not_analyzed_tables",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "Tables Need Index",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "parser": "backend",
       "source": "url",
       "type": "json",
       "url": "/table_need_index",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    }
   ]
  },
  {
   "title": "Spill File Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spill count per segment",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "parser": "backend",
       "source": "url",
       "type": "json",
       "url": "/spill_count_per_primary_seg",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "Total Spill File Size (Cluster)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "columns": [
        { "selector": "", "text": "", "type": "string" }
       ],
       "computed_columns": [
        { "selector": "", "text": "", "type": "string" }
       ],
       "parser": "backend",
       "source": "url",
       "type": "json",
       "url": "/spill_count_per_primary_seg",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Write Utilization",
     "type": "timeseries",
     "description": "This panel shows the percentage of time the disk spent doing write operations over the last 5 minutes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "rate(warehousepg_observability_node_disk_write_time_seconds_total[5m])*100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Read Utilization",
     "type": "timeseries",
     "description": "This panel shows the percentage of time the disk spent doing read operations over the last 5 minutes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "rate(warehousepg_observability_node_disk_read_time_seconds_total[5m])*100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Current Disk I/O for each host",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "warehousepg_observability_node_disk_io_now",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "File system device error",
     "type": "timeseries",
     "description": "total number of filesystem or device errors across all monitored disks and partitions for each server",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum(warehousepg_observability_node_filesystem_device_error) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilisation for every Host",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (\n  avg by (instance) (\n    rate(warehousepg_observability_node_cpu_seconds_total{mode=\"idle\"}[15m])\n  ) * 100\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Current CPU Utilisation for every Host",
     "type": "stat",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (\n  avg by (instance) (\n    rate(warehousepg_observability_node_cpu_seconds_total{mode=\"idle\"}[5m])\n  ) * 100\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Load Average Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "System Load (1min avg)",
   "type": "timeseries",
   "description": "The average number of processes that are in the run queue over a specific time period using 1 min rolling average",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "warehousepg_observability_node_load1",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Load (5min avg)",
   "type": "timeseries",
   "description": "The average number of processes that are in the run queue over a specific time period using 5 min rolling average",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "warehousepg_observability_node_load5",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Load (15min avg)",
   "type": "timeseries",
   "description": "The average number of processes that are in the run queue over a specific time period using 15 min rolling average",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "warehousepg_observability_node_load15",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Swap Memory Usage by Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Available Swap Memory",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "warehousepg_observability_node_memory_SwapFree_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Swap Memory",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "warehousepg_observability_node_memory_SwapTotal_bytes-warehousepg_observability_node_memory_SwapFree_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}