{
 "title": "WarehousePG-Logs-Dashboard",
 "tags": [ "whpg" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataSourcePrometheus", "label": "DataSourcePrometheus", "query": "prometheus" },
   {
    "name": "DataSourceInfinity",
    "label": "DataSourceInfinity",
    "query": "yesoreyeram-infinity-datasource"
   },
   { "name": "DataSourceLoki", "label": "DataSourceLoki", "query": "loki" },
   {
    "name": "HostList",
    "label": "HostList",
    "query": {}
   },
   {
    "name": "SeverityList",
    "label": "SeverityList",
    "query": {}
   },
   {
    "name": "SegmentNameList",
    "label": "SegmentNameList",
    "query": {}
   },
   {
    "name": "ListFileName",
    "label": "ListFileName",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Log Volume in Selected Time Range for segments($SegmentNameList) with severity ($SeverityList)",
     "type": "stat",
     "description": "Displays the total number of log events produced across all selected segments and severities during the dashboard’s currently selected time window.\nUseful for understanding total cluster log activity over the chosen period (e.g., last 1h, last 24h).",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(\n  count_over_time({segment=~\"$SegmentNameList\", severity=~\"$SeverityList\"}[$__range])\n)",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Total Log Volume in Selected Time Range for Host($HostList) with severity ($SeverityList)",
     "type": "stat",
     "description": "Displays the total number of log events produced across all selected Hosts and severities during the dashboard’s currently selected time window.\nUseful for understanding total cluster log activity over the chosen period (e.g., last 1h, last 24h).\n",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({hostname=~\"$HostList\", severity=~\"$SeverityList\"}[$__range]))",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Total Log Volume in Selected Time Range for Host($HostList) with FATAL severity ",
     "type": "stat",
     "description": "Displays the total number of log events produced across all selected Hosts and FATAL severity during the dashboard’s currently selected time window.\nUseful for understanding total cluster log activity over the chosen period (e.g., last 1h, last 24h).\n",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({hostname=~\"$HostList\", severity=\"$FATAL\"}[$__range]))",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Total Log Volume in Selected Time Range for Host($HostList) with PANIC severity ",
     "type": "stat",
     "description": "Displays the total number of log events produced across all selected Hosts and PANIC severity during the dashboard’s currently selected time window.\nUseful for understanding total cluster log activity over the chosen period (e.g., last 1h, last 24h).\n",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({hostname=~\"$HostList\", severity=\"$PANIC\"}[$__range]))",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Current Log Volume (1-Minute Window) for Host($HostList) with Severity($SeverityList) ",
     "type": "gauge",
     "description": "Displays the number of logs generated on selected host over the last 1 minute, filtered by the selected severity levels.\nUseful for monitoring real-time activity and quickly spotting hosts with unusually high log output.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({hostname=~\"$HostList\", severity=~\"$SeverityList\"}[1m])) by (hostname)",
       "legendFormat": "{{hostname}} "
      }
     ]
    },
    {
     "title": "Current Log Volume (1-Minute Window) for Segment($HostList) with Severity($SeverityList) ",
     "type": "gauge",
     "description": "Displays the number of logs generated on selected segments over the last 1 minute, filtered by the selected severity levels.\nUseful for monitoring real-time activity and quickly spotting segments with unusually high log output.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({segment=~\"$SegmentNameList\", severity=~\"$SeverityList\"}[1m])) by (segment)",
       "legendFormat": "{{segment}}"
      }
     ]
    }
   ]
  },
  { "title": "Segment View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": " Log for Segment ($SegmentNameList ) with Severity($SeverityList)",
   "type": "logs",
   "description": "Shows all log lines from the segments selected in the segment list dropdown that contain the severity as per SeverityList",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{segment=~\"$SegmentNameList\", severity=~\"$SeverityList\"} ",
     "legendFormat": "{{segment}} "
    }
   ]
  },
  {
   "title": "Log Volume (Rolling 5-Minute Window) per Segment($SegmentNameList) with Severity($SeverityList)",
   "type": "timeseries",
   "description": "Shows the number of log entries generated per segment within a continuous 5-minute sliding window.\nThis helps detect sudden spikes in logs and provides real-time visibility into segment-level activity.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({segment=~\"$SegmentNameList\", severity=~\"$SeverityList\"}[5m])) by (segment)",
     "legendFormat": "{{segment}} "
    }
   ]
  },
  {
   "title": "Host View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": " Log for Host ($HostList ) with Severity($SeverityList)",
     "type": "logs",
     "description": "Shows all log lines from the servers selected in the HostList dropdown that contain the severity as per SeverityList",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 224 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{hostname=~\"$HostList\", severity=~\"$SeverityList\"} "
      }
     ]
    },
    {
     "title": "Log Volume (Rolling 5-Minute Window) per Host($HostList) with Severity($SeverityList)",
     "type": "timeseries",
     "description": "Shows the number of log entries generated per Host within a continuous 5-minute sliding window. This helps detect sudden spikes in logs and provides real-time visibility into Host-level activity.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 252 },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({hostname=~\"$HostList\", severity=~\"$SeverityList\"}[5m])) by (hostname)",
       "legendFormat": "{{hostname}} "
      }
     ]
    }
   ]
  },
  {
   "title": "File View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": " Log for File ($ListFileName ) with Severity($SeverityList)",
     "type": "logs",
     "description": "Shows all log lines from the files selected in the ListFileName dropdown that contain the severity as per SeverityList",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 225 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{filename=~\"$ListFileName\", severity=~\"$SeverityList\"} ",
       "legendFormat": "{{filename}} "
      }
     ]
    },
    {
     "title": "Log events for Current Log Volume  (1-Minute Window) for each selected File($ListFileName) with Severity($SeverityList)",
     "type": "bargauge",
     "description": "Displays the number of logs enteries on each file over the last 1 minute, filtered by the selected severity levels.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 235 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({filename=~\"$ListFileName\", severity=~\"$SeverityList\"}[1m])) by (filename)",
       "legendFormat": "{{filename}} "
      }
     ]
    }
   ]
  }
 ]
}