{
 "title": "WarehousePG-Overview",
 "tags": [ "whpg" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSourcePrometheus", "label": "DataSourcePrometheus", "query": "prometheus" },
   {
    "name": "DataSourceInfinity",
    "label": "DataSourceInfinity",
    "query": "yesoreyeram-infinity-datasource"
   },
   { "name": "DataSourceLoki", "label": "DataSourceLoki", "query": "loki" },
   {
    "name": "HostMountPoints",
    "label": "HostMountPoints",
    "query": {
     "query": "label_values(warehousepg_observability_node_filesystem_free_bytes,mountpoint)"
    }
   },
   {
    "name": "HostList",
    "label": "HostList",
    "query": {
     "query": "label_values(warehousepg_observability_node_filesystem_free_bytes,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://warehouse-pg.io/fulllogo_transparent_small_buffer.png\">"
   }
  },
  {
   "type": "stat",
   "description": "DB Connection Status",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(warehousepg_observability_coordinator_total_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "warehousepg_observability_connected",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Cluster Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Coordinator Status",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "warehousepg_observability_coordinator_curr_active_up_count",
       "legendFormat": "Primary Status"
      },
      {
       "expr": "warehousepg_observability_coordinator_curr_standby_up_count",
       "legendFormat": "Standby Status"
      },
      {
       "expr": "warehousepg_observability_coordinator_failed_over_count",
       "legendFormat": "Working In Failed Over State"
      }
     ]
    },
    {
     "title": "Segment Status",
     "type": "stat",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "warehousepg_observability_clinfo_total_primary_count",
       "legendFormat": "Total Primary Segments"
      },
      {
       "expr": "warehousepg_observability_clinfo_total_primary_count - warehousepg_observability_clinfo_curr_primary_down_count",
       "legendFormat": "Primary Segments Up"
      },
      {
       "expr": "warehousepg_observability_clinfo_curr_primary_down_count",
       "legendFormat": "Primary Segments Down"
      },
      {
       "expr": "warehousepg_observability_clinfo_preff_primary_up_count",
       "legendFormat": "Preferred Primary UP"
      },
      {
       "expr": "warehousepg_observability_clinfo_primary_not_in_sync_count",
       "legendFormat": "Primary Not In Sync"
      },
      {
       "expr": "warehousepg_observability_clinfo_total_mirror_count",
       "legendFormat": "Total Mirror Segments"
      },
      {
       "expr": "warehousepg_observability_clinfo_curr_mirror_up_count",
       "legendFormat": "Mirror Segments Up"
      },
      {
       "expr": "warehousepg_observability_clinfo_curr_mirror_down_count",
       "legendFormat": "Mirror Segments Down"
      },
      {
       "expr": "warehousepg_observability_clinfo_promoted_mirror_count",
       "legendFormat": "Promoted Mirror"
      },
      {
       "expr": "warehousepg_observability_clinfo_mirror_not_in_sync_count",
       "legendFormat": "Mirror Not In Sync"
      }
     ]
    },
    {
     "title": "Segment Status Timeline",
     "type": "state-timeline",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "warehousepg_observability_seg_status",
       "legendFormat": "{{gp_segment_desc}} ({{role}})"
      }
     ]
    },
    {
     "title": "Connections Per User",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 24 },
     "targets": [
      { "expr": "warehousepg_observability_qu", "legendFormat": "{{username}}" }
     ]
    },
    {
     "title": "Database Size",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "warehousepg_observability_db_size",
       "legendFormat": "{{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free Disk Space(Host View) For Mount Point  - $HostMountPoints ",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "warehousepg_observability_node_filesystem_free_bytes{instance=~\".+\", mountpoint=~\"$HostMountPoints\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Free Disk Space (Device View) for Host - $HostList",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "warehousepg_observability_node_filesystem_free_bytes{instance=~\"$HostList\", device=~\".+\"}",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Load (1min avg)",
     "type": "stat",
     "description": "The average number of processes that are in the run queue over a specific time period using 1 min rolling average across cluster",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(warehousepg_observability_node_load1)",
       "legendFormat": "Cluster Load (1m)"
      }
     ]
    },
    {
     "title": "System Load (5min avg)",
     "type": "stat",
     "description": "The average number of processes that are in the run queue over a specific time period using 5 min rolling average across cluster",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(warehousepg_observability_node_load5)",
       "legendFormat": "Cluster Load (5m)"
      }
     ]
    },
    {
     "title": "System Load (15min avg)",
     "type": "stat",
     "description": "The average number of processes that are in the run queue over a specific time period using 15 min rolling average across cluster",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(warehousepg_observability_node_load15)",
       "legendFormat": "Cluster Load (15m)"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "warehousepg_observability_q_total",
       "legendFormat": "Total Queries"
      },
      {
       "expr": "warehousepg_observability_q_active",
       "legendFormat": "Active Queries"
      },
      {
       "expr": "warehousepg_observability_q_idle",
       "legendFormat": "Idle Queries"
      },
      {
       "expr": "warehousepg_observability_q_long_running_120s",
       "legendFormat": "Long Running Queries(>120s)"
      },
      {
       "expr": "warehousepg_observability_q_in_wait",
       "legendFormat": "Queries in Wait"
      },
      {
       "expr": "warehousepg_observability_q_blocked",
       "legendFormat": "Blocked Queries"
      }
     ]
    },
    {
     "title": "Queries Per Second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "targets": [
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Queries per user",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "targets": [
      { "expr": "warehousepg_observability_qu", "legendFormat": "{{username}}" }
     ]
    },
    {
     "title": "Queries Overview",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "warehousepg_observability_q_active",
       "legendFormat": "Active queries"
      },
      {
       "expr": "warehousepg_observability_q_idle",
       "legendFormat": "Idle queries"
      }
     ]
    },
    {
     "title": "Longest Running Query",
     "type": "table",
     "description": "This table shows the list of longest running queries.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "parser": "backend",
       "source": "url",
       "type": "json",
       "url": "/pg_stat_activity",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    }
   ]
  },
  {
   "title": "Log Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "LOG Severity Count",
     "type": "stat",
     "description": "Displays the total number of LOG-level messages generated across the cluster during the selected dashboard time range.",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 144 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({severity=\"LOG\"}[${__range}]))"
      }
     ]
    },
    {
     "title": "ERROR Severity Count",
     "type": "stat",
     "description": "Displays the total number of ERROR-level messages generated across the cluster during the selected dashboard time range.",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 144 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({severity=\"ERROR\"}[${__range}]))"
      }
     ]
    },
    {
     "title": "FATAL Severity Count",
     "type": "stat",
     "description": "Displays the total number of FATAL-level messages generated across the cluster during the selected dashboard time range",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 144 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({severity=\"FATAL\"}[${__range}]))"
      }
     ]
    },
    {
     "title": "PANIC Severity Count",
     "type": "stat",
     "description": "Displays the total number of PANIC-level messages generated across the cluster during the selected dashboard time range",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 144 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({severity=\"PANIC\"}[${__range}]))"
      }
     ]
    }
   ]
  }
 ]
}