{
 "title": "WHPG Resource Details",
 "tags": [ "WHPG" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DataSourcePrometheus", "label": "DataSourcePrometheus", "query": "prometheus" },
   {
    "name": "DataSourceInfinity",
    "label": "DataSourceInfinity",
    "query": "yesoreyeram-infinity-datasource"
   },
   {
    "name": "resource_group",
    "label": "Resource Group",
    "query": {
     "query": "label_values(warehousepg_observability_resgroup_status_cpu_max_pt,groupname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "warehousepg_observability_resgroup_host_memory_usage{groupname=\"$resource_group\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Concurrency Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "warehousepg_observability_resgroup_status_concurrency{groupname=\"$resource_group\"}",
     "legendFormat": "Concurrency Limit"
    },
    {
     "expr": "warehousepg_observability_resgroup_status_running_queries{groupname=\"$resource_group\"}",
     "legendFormat": "Running queries"
    },
    {
     "expr": "warehousepg_observability_resgroup_status_queued_queries{groupname=\"$resource_group\"}",
     "legendFormat": "Queued Quries"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "warehousepg_observability_resgroup_status_cpu_max_pt{groupname=\"$resource_group\"}",
     "legendFormat": "Max CPU Limit"
    },
    {
     "expr": "warehousepg_observability_resgroup_host_cpu_usage{groupname=\"$resource_group\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Resource Group Configurations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/resgroup_config",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}