{
 "title": "WHPG Resource Group Details",
 "tags": [ "WHPG" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DataSourcePrometheus", "label": "DataSourcePrometheus", "query": "prometheus" },
   {
    "name": "DataSourceInfinity",
    "label": "DataSourceInfinity",
    "query": "yesoreyeram-infinity-datasource"
   },
   {
    "name": "resource_group",
    "label": "Resource Group",
    "query": {
     "query": "label_values(warehousepg_observability_resgroup_status_cpu_max_pt,groupname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://warehouse-pg.io/fulllogo_transparent_small_buffer.png\">"
   }
  },
  {
   "type": "stat",
   "description": "DB Connection Status",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(warehousepg_observability_coordinator_total_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "DB Connection Status",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(warehousepg_observability_qu)",
     "legendFormat": "# Connections"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 10, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "warehousepg_observability_connected{observability!=\"N/A\"}",
     "legendFormat": "  "
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "warehousepg_observability_connected{observability!=\"N/A\"}",
     "legendFormat": "  "
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "expr": "warehousepg_observability_connected{observability!=\"N/A\"}",
     "legendFormat": "  "
    }
   ]
  },
  { "title": "Resource Groups Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "warehousepg_observability_resgroup_host_memory_usage{groupname=\"$resource_group\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Concurrency Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "warehousepg_observability_resgroup_status_concurrency{groupname=\"$resource_group\"}",
     "legendFormat": "Concurrency Limit"
    },
    {
     "expr": "warehousepg_observability_resgroup_status_running_queries{groupname=\"$resource_group\"}",
     "legendFormat": "Running queries"
    },
    {
     "expr": "warehousepg_observability_resgroup_status_queued_queries{groupname=\"$resource_group\"}",
     "legendFormat": "Queued Queries"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "warehousepg_observability_resgroup_status_cpu_max_pt{groupname=\"$resource_group\"}",
     "legendFormat": "Max CPU Limit"
    },
    {
     "expr": "warehousepg_observability_resgroup_host_cpu_usage{groupname=\"$resource_group\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Resource Group Configurations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/resgroup_config",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}