{
 "title": "WHPG Cluster Dashboard",
 "tags": [ "WHPG" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DataSourcePrometheus", "label": "DataSourcePrometheus", "query": "prometheus" },
   {
    "name": "DataSourceInfinity",
    "label": "DataSourceInfinity",
    "query": "yesoreyeram-infinity-datasource"
   },
   { "name": "DataSourceLoki", "label": "DataSourceLoki", "query": "loki" },
   {
    "name": "HostMountPoints",
    "label": "HostMountPoints",
    "query": {
     "query": "label_values(warehousepg_observability_node_filesystem_free_bytes,mountpoint)"
    }
   },
   {
    "name": "HostList",
    "label": "HostList",
    "query": {
     "query": "label_values(warehousepg_observability_node_filesystem_free_bytes,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title?", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://warehouse-pg.io/fulllogo_transparent_small_buffer.png\">"
   }
  },
  {
   "type": "stat",
   "description": "DB Connection Status",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(warehousepg_observability_coordinator_total_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "DB Connection Status",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(warehousepg_observability_qu)",
     "legendFormat": "# Connections"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 10, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "warehousepg_observability_connected{observability!=\"N/A\"}",
     "legendFormat": "  "
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "warehousepg_observability_connected{observability!=\"N/A\"}",
     "legendFormat": "  "
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "expr": "warehousepg_observability_connected{observability!=\"N/A\"}",
     "legendFormat": "  "
    }
   ]
  },
  { "title": "Cluster Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Coordinator Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "warehousepg_observability_coordinator_curr_active_up_count",
     "legendFormat": "Primary Status"
    },
    {
     "expr": "warehousepg_observability_coordinator_curr_standby_up_count",
     "legendFormat": "Standby Status"
    },
    {
     "expr": "warehousepg_observability_coordinator_failed_over_count",
     "legendFormat": "Working In Failed Over State"
    }
   ]
  },
  {
   "title": "System Load (15 min avg)",
   "type": "timeseries",
   "description": "The average number of processes that are in the run queue over a specific time period using 15 min rolling average",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 4 },
   "targets": [
    {
     "expr": "avg by (instance) (warehousepg_observability_node_load15)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Utilization per Host (15 min Avg)",
   "type": "timeseries",
   "description": "Shows the percentage of CPU currently in use per instance, calculated as 100 - %idle over the last 15 minutes. This provides a 15-minute rolling average of CPU utilization across the system.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (\n  avg by (instance) (\n    rate(warehousepg_observability_node_cpu_seconds_total{mode=\"idle\"}[15m])\n  ) * 100\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Primary Segment Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "warehousepg_observability_clinfo_total_primary_count",
     "legendFormat": "Total Primary Segments"
    },
    {
     "expr": "warehousepg_observability_clinfo_total_primary_count - warehousepg_observability_clinfo_curr_primary_down_count",
     "legendFormat": "Primary Segments Up"
    },
    {
     "expr": "warehousepg_observability_clinfo_curr_primary_down_count",
     "legendFormat": "Primary Segments Down"
    },
    {
     "expr": "warehousepg_observability_clinfo_preff_primary_up_count",
     "legendFormat": "Preferred Primary UP"
    },
    {
     "expr": "warehousepg_observability_clinfo_primary_not_in_sync_count",
     "legendFormat": "Primary Not In Sync"
    }
   ]
  },
  {
   "title": "Queries Overview (last 24 hours)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 12 },
   "targets": [
    {
     "expr": "warehousepg_observability_q_active",
     "legendFormat": "Active queries"
    },
    {
     "expr": "warehousepg_observability_q_idle",
     "legendFormat": "Idle queries"
    }
   ]
  },
  {
   "title": "Log Severity Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({severity=\"FATAL\"}[${__range}]))",
     "legendFormat": "FATAL"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({severity=\"PANIC\"}[${__range}]))",
     "legendFormat": "PANIC"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({severity=\"ERROR\"}[${__range}]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "Mirror Segment Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "warehousepg_observability_clinfo_total_mirror_count",
     "legendFormat": "Total Mirror Segments"
    },
    {
     "expr": "warehousepg_observability_clinfo_curr_mirror_up_count",
     "legendFormat": "Mirror Segments Up"
    },
    {
     "expr": "warehousepg_observability_clinfo_curr_mirror_down_count",
     "legendFormat": "Mirror Segments Down"
    },
    {
     "expr": "warehousepg_observability_clinfo_promoted_mirror_count",
     "legendFormat": "Promoted Mirror"
    },
    {
     "expr": "warehousepg_observability_clinfo_mirror_not_in_sync_count",
     "legendFormat": "Mirror Not In Sync"
    }
   ]
  },
  {
   "title": "System Load (1 min avg)",
   "type": "stat",
   "description": "The average number of processes that are in the run queue over a specific time period using 1 min rolling average across cluster",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(warehousepg_observability_node_load1)",
     "legendFormat": "Cluster Load (1m)"
    }
   ]
  },
  {
   "title": "System Load (5 min avg)",
   "type": "stat",
   "description": "The average number of processes that are in the run queue over a specific time period using 5 min rolling average across cluster",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(warehousepg_observability_node_load5)",
     "legendFormat": "Cluster Load (5m)"
    }
   ]
  },
  {
   "title": "System Load (15 min avg)",
   "type": "stat",
   "description": "The average number of processes that are in the run queue over a specific time period using 15 min rolling average across cluster",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(warehousepg_observability_node_load15)",
     "legendFormat": "Cluster Load (15m)"
    }
   ]
  },
  { "title": "Query Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "warehousepg_observability_q_total",
     "legendFormat": "Total Queries"
    },
    {
     "expr": "warehousepg_observability_q_active",
     "legendFormat": "Active Queries"
    },
    {
     "expr": "warehousepg_observability_q_idle",
     "legendFormat": "Idle Queries"
    },
    {
     "expr": "warehousepg_observability_q_long_running_120s",
     "legendFormat": "Long Running Queries(>120s)"
    },
    {
     "expr": "warehousepg_observability_q_in_wait",
     "legendFormat": "Queries in Wait"
    },
    {
     "expr": "warehousepg_observability_q_blocked",
     "legendFormat": "Blocked Queries"
    }
   ]
  },
  {
   "title": "Query Per Second (5 min rate)",
   "type": "timeseries",
   "description": "Measures the average number of queries executed per second over the last 5 minutes.\nThis metric is calculated using a monotonically increasing counter on total transactions(commit+rollback). A higher value indicates increased workload on the cluster. ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(warehousepg_observability_txn_total_queries_executed[5m])",
     "legendFormat": "Active queries"
    }
   ]
  },
  {
   "title": "Queries per user",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "targets": [
    { "expr": "warehousepg_observability_qu", "legendFormat": "{{username}}" }
   ]
  },
  { "title": "Disk Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Cumulative Disk Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (warehousepg_observability_node_filesystem_avail_bytes{ mountpoint=~\"$HostMountPoints\"} / warehousepg_observability_node_filesystem_size_bytes{ mountpoint=~\"$HostMountPoints\"})) * 100",
     "legendFormat": "{{instance}}{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Cumulative Disk Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(warehousepg_observability_node_filesystem_avail_bytes)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(warehousepg_observability_node_filesystem_size_bytes)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Free Disk Space(Host View) For Mount Point  - $HostMountPoints ",
   "type": "table",
   "description": "Shows the amount of free disk space available on the specified mount points for each host instance. This metric helps monitor storage capacity and detect low-disk conditions that may impact database performance or availability.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "warehousepg_observability_node_filesystem_free_bytes{instance=~\".+\", mountpoint=~\"$HostMountPoints\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Free Disk Space (Device View) for Host - $HostList",
   "type": "table",
   "description": "Shows the amount of free disk space available on all filesystem devices for the selected host instance. This metric helps track storage usage and identify when a host is running low on available disk space, which can affect database performance, logging, and overall system stability.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "warehousepg_observability_node_filesystem_free_bytes{instance=~\"$HostList\", device=~\".+\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Cumulative Memory Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  (warehousepg_observability_node_memory_MemTotal_bytes - warehousepg_observability_node_memory_MemFree_bytes - (warehousepg_observability_node_memory_Cached_bytes + warehousepg_observability_node_memory_Buffers_bytes + warehousepg_observability_node_memory_SReclaimable_bytes))\n  /\n  warehousepg_observability_node_memory_MemTotal_bytes\n) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cumulative Swap Memory Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  (warehousepg_observability_node_memory_SwapTotal_bytes - warehousepg_observability_node_memory_SwapFree_bytes)\n  /\n  warehousepg_observability_node_memory_SwapTotal_bytes\n) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}