{
 "title": "WHPG Query Details",
 "tags": [ "WHPG" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DataSourcePrometheus", "label": "DataSourcePrometheus", "query": "prometheus" },
   {
    "name": "DataSourceInfinity",
    "label": "DataSourceInfinity",
    "query": "yesoreyeram-infinity-datasource"
   },
   { "name": "DataSourceLoki", "label": "DataSourceLoki", "query": "loki" },
   {
    "name": "HostList",
    "label": "HostList",
    "query": {
     "query": "label_values(warehousepg_observability_node_filesystem_free_bytes,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://warehouse-pg.io/fulllogo_transparent_small_buffer.png\">"
   }
  },
  {
   "type": "stat",
   "description": "DB Connection Status",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(warehousepg_observability_coordinator_total_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "DB Connection Status",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(warehousepg_observability_qu)",
     "legendFormat": "# Connections"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 10, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "warehousepg_observability_connected{observability!=\"N/A\"}",
     "legendFormat": "  "
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "warehousepg_observability_connected{observability!=\"N/A\"}",
     "legendFormat": "  "
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "expr": "warehousepg_observability_connected{observability!=\"N/A\"}",
     "legendFormat": "  "
    }
   ]
  },
  { "title": "Query Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "warehousepg_observability_q_total",
     "legendFormat": "Total Queries"
    },
    {
     "expr": "warehousepg_observability_q_active",
     "legendFormat": "Active Queries"
    },
    {
     "expr": "warehousepg_observability_q_idle",
     "legendFormat": "Idle Queries"
    },
    {
     "expr": "warehousepg_observability_q_long_running_120s",
     "legendFormat": "Long Running Queries(>120s)"
    },
    {
     "expr": "warehousepg_observability_q_in_wait",
     "legendFormat": "Queries in Wait"
    },
    {
     "expr": "warehousepg_observability_q_blocked",
     "legendFormat": "Blocked Queries"
    }
   ]
  },
  {
   "title": "Connections Per User",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "warehousepg_observability_qu", "legendFormat": "{{username}}" }
   ]
  },
  {
   "title": "Queries per user",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "warehousepg_observability_qu", "legendFormat": "{{username}}" }
   ]
  },
  {
   "title": "Queries Overview",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "warehousepg_observability_q_active",
     "legendFormat": "Active queries"
    },
    {
     "expr": "warehousepg_observability_q_idle",
     "legendFormat": "Idle queries"
    }
   ]
  },
  {
   "title": "Queries Per Second (5 min rate)",
   "type": "timeseries",
   "description": "Measures the average number of queries executed per second over the last 5 minutes.\nThis metric is calculated using a monotonically increasing counter on total transactions(commit+rollback). A higher value indicates increased workload on the cluster. ",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate(warehousepg_observability_txn_total_queries_executed[5m])",
     "legendFormat": "QPS (5m rate)"
    }
   ]
  },
  { "title": "Query Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Current Running Queries",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/current_running_queries",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Long Running Queries",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/long_running_queries",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Blocked Queries",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/block_queries",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}