{
 "title": "WHPG Log Details",
 "tags": [ "WHPG" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DataSourcePrometheus", "label": "DataSourcePrometheus", "query": "prometheus" },
   { "name": "DataSourceLoki", "label": "DataSourceLoki", "query": "loki" },
   {
    "name": "HostList",
    "label": "HostList",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://warehouse-pg.io/fulllogo_transparent_small_buffer.png\">"
   }
  },
  {
   "type": "stat",
   "description": "DB Connection Status",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(warehousepg_observability_coordinator_total_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "DB Connection Status",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(warehousepg_observability_qu)",
     "legendFormat": "# Connections"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 10, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "warehousepg_observability_connected{observability!=\"N/A\"}",
     "legendFormat": "  "
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "warehousepg_observability_connected{observability!=\"N/A\"}",
     "legendFormat": "  "
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "expr": "warehousepg_observability_connected{observability!=\"N/A\"}",
     "legendFormat": "  "
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Cumulative Log Severity Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 4 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({severity=\"FATAL\"}[${__range}]))",
     "legendFormat": "FATAL"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({severity=\"PANIC\"}[${__range}]))",
     "legendFormat": "PANIC"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({severity=\"ERROR\"}[${__range}]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "PANIC Logs per Host",
   "type": "timeseries",
   "description": "Shows the number of log entries generated per Host within a continuous 5-minute sliding window. This helps detect sudden spikes in logs and provides real-time visibility into Host-level activity.",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 4 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({hostname=~\".+\", severity=~\"PANIC\"}[5m])) by (hostname)",
     "legendFormat": "{{hostname}} "
    }
   ]
  },
  {
   "title": "FATAL Logs per Host",
   "type": "timeseries",
   "description": "Shows the number of log entries generated per Host within a continuous 5-minute sliding window. This helps detect sudden spikes in logs and provides real-time visibility into Host-level activity.",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({hostname=~\".+\", severity=~\"FATAL\"}[5m])) by (hostname)",
     "legendFormat": "{{hostname}} "
    }
   ]
  },
  {
   "title": "ERROR Logs per Host",
   "type": "timeseries",
   "description": "Shows the number of log entries generated per Host within a continuous 5-minute sliding window. This helps detect sudden spikes in logs and provides real-time visibility into Host-level activity.",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({hostname=~\".+\", severity=~\"ERROR\"}[5m])) by (hostname)",
     "legendFormat": "{{hostname}} "
    }
   ]
  },
  { "title": "Host View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "PANIC, FATAL, ERROR Logs for Host ($HostList)",
   "type": "logs",
   "description": "Shows all log lines from the servers selected in the HostList dropdown that contain the severity as per SeverityList",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{hostname=~\"$HostList\", severity=~\"ERROR|FATAL|PANIC\"} "
    }
   ]
  },
  {
   "title": "Log Volume (Rolling 5-Minute Window) per Host($HostList) ",
   "type": "timeseries",
   "description": "Shows the number of log entries generated per Host within a continuous 5-minute sliding window. This helps detect sudden spikes in logs and provides real-time visibility into Host-level activity.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({hostname=~\"$HostList\", severity=~\"FATAL\"}[5m])) by (hostname)",
     "legendFormat": "FATAL"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({hostname=~\"$HostList\", severity=~\"ERROR\"}[5m])) by (hostname)",
     "legendFormat": "ERROR"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({hostname=~\"$HostList\", severity=~\"PANIC\"}[5m])) by (hostname)",
     "legendFormat": "PANIC"
    }
   ]
  }
 ]
}