{
 "title": "WHPG Segment Details",
 "tags": [ "WHPG" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DataSourcePrometheus", "label": "DataSourcePrometheus", "query": "prometheus" },
   {
    "name": "DataSourceInfinity",
    "label": "DataSourceInfinity",
    "query": "yesoreyeram-infinity-datasource"
   },
   { "name": "DataSourceLoki", "label": "DataSourceLoki", "query": "loki" },
   {
    "name": "HostMountPoints",
    "label": "HostMountPoints",
    "query": {
     "query": "label_values(warehousepg_observability_node_filesystem_free_bytes,mountpoint)"
    }
   },
   {
    "name": "HostList",
    "label": "HostList",
    "query": {
     "query": "label_values(warehousepg_observability_node_filesystem_free_bytes,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://warehouse-pg.io/fulllogo_transparent_small_buffer.png\">"
   }
  },
  {
   "type": "stat",
   "description": "DB Connection Status",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(warehousepg_observability_coordinator_total_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "DB Connection Status",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(warehousepg_observability_qu)",
     "legendFormat": "# Connections"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 10, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "warehousepg_observability_connected{observability!=\"N/A\"}",
     "legendFormat": "  "
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "warehousepg_observability_connected{observability!=\"N/A\"}",
     "legendFormat": "  "
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "expr": "warehousepg_observability_connected{observability!=\"N/A\"}",
     "legendFormat": "  "
    }
   ]
  },
  { "title": "Segment Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Segment Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "warehousepg_observability_clinfo_total_primary_count",
     "legendFormat": "Total Primary Segments"
    },
    {
     "expr": "warehousepg_observability_clinfo_total_primary_count - warehousepg_observability_clinfo_curr_primary_down_count",
     "legendFormat": "Primary Segments Up"
    },
    {
     "expr": "warehousepg_observability_clinfo_curr_primary_down_count",
     "legendFormat": "Primary Segments Down"
    },
    {
     "expr": "warehousepg_observability_clinfo_preff_primary_up_count",
     "legendFormat": "Preferred Primary UP"
    },
    {
     "expr": "warehousepg_observability_clinfo_primary_not_in_sync_count",
     "legendFormat": "Primary Not In Sync"
    },
    {
     "expr": "warehousepg_observability_clinfo_total_mirror_count",
     "legendFormat": "Total Mirror Segments"
    },
    {
     "expr": "warehousepg_observability_clinfo_curr_mirror_up_count",
     "legendFormat": "Mirror Segments Up"
    },
    {
     "expr": "warehousepg_observability_clinfo_curr_mirror_down_count",
     "legendFormat": "Mirror Segments Down"
    },
    {
     "expr": "warehousepg_observability_clinfo_promoted_mirror_count",
     "legendFormat": "Promoted Mirror"
    },
    {
     "expr": "warehousepg_observability_clinfo_mirror_not_in_sync_count",
     "legendFormat": "Mirror Not In Sync"
    }
   ]
  },
  {
   "title": "Segment Status Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 4 },
   "targets": [
    {
     "expr": "warehousepg_observability_seg_status",
     "legendFormat": "{{gp_segment_desc}} ({{role}})"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "warehousepg_observability_db_size",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Segment Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "warehousepg_observability_seg_status",
     "legendFormat": "{{gp_segment_desc}} ({{role}})"
    }
   ]
  },
  { "title": "System Load Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "System Load 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "warehousepg_observability_node_load1",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Load 5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "warehousepg_observability_node_load5",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Load 15",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "warehousepg_observability_node_load15",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "CPU Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "CPU Utilization for every Host (Current)",
   "type": "stat",
   "description": "Shows the percentage of CPU actively used on each host, calculated as 100 - %idle over the last 5 minutes. ",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg by (instance) (\n    rate(warehousepg_observability_node_cpu_seconds_total{mode=\"idle\"}[5m])\n  ) * 100\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Utilization per Host (15-min Avg)",
   "type": "timeseries",
   "description": "Shows the percentage of CPU currently in use per instance, calculated as 100 - %idle over the last 15 minutes. This provides a 15-minute rolling average of CPU utilization across the system.",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (\n  avg by (instance) (\n    rate(warehousepg_observability_node_cpu_seconds_total{mode=\"idle\"}[15m])\n  ) * 100\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Disk Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Disk Write Utilization (%)",
   "type": "timeseries",
   "description": "This panel shows the percentage of time the disk spent doing write operations averagedover the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance) (\n  rate(warehousepg_observability_node_disk_write_time_seconds_total[5m]) * 100\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Read Utilization (%)",
   "type": "timeseries",
   "description": "This panel shows the percentage of time the disk spent doing read operations averaged over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance) (\n  rate(warehousepg_observability_node_disk_read_time_seconds_total[5m])*100\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "File System Device Error",
   "type": "timeseries",
   "description": "This panel shows total number of filesystem or device errors across all monitored disks and partitions for each server",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum(warehousepg_observability_node_filesystem_device_error) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Disk I/O for each host",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum by (instance) (warehousepg_observability_node_disk_io_now)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Free Disk Space(Host View) For Mount Point  - $HostMountPoints ",
   "type": "table",
   "description": "Shows the amount of free disk space available on the specified mount points for each host instance. This metric helps monitor storage capacity and detect low-disk conditions that may impact database performance or availability.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "warehousepg_observability_node_filesystem_free_bytes{instance=~\".+\", mountpoint=~\"$HostMountPoints\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Free Disk Space (Device View) for Host - $HostList",
   "type": "table",
   "description": "Shows the amount of free disk space available on all filesystem devices for the selected host instance. This metric helps track storage usage and identify when a host is running low on available disk space, which can affect database performance, logging, and overall system stability.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "warehousepg_observability_node_filesystem_free_bytes{instance=~\"$HostList\", device=~\".+\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  (warehousepg_observability_node_memory_MemTotal_bytes - warehousepg_observability_node_memory_MemFree_bytes - (warehousepg_observability_node_memory_Cached_bytes + warehousepg_observability_node_memory_Buffers_bytes + warehousepg_observability_node_memory_SReclaimable_bytes))\n  /\n  warehousepg_observability_node_memory_MemTotal_bytes\n) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Swap Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  (warehousepg_observability_node_memory_SwapTotal_bytes - warehousepg_observability_node_memory_SwapFree_bytes)\n  /\n  warehousepg_observability_node_memory_SwapTotal_bytes\n) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Spill Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Spill File Usage per Segment",
   "type": "table",
   "description": "Displays the total number of workfile spill files and total spill size (in bytes) for each segment in the cluster. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/spill_count_per_primary_seg",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Top Queries by Spill Usage",
   "type": "table",
   "description": "Shows the top 20 queries generating workfile spills in the cluster.  If no active spill queries exist, a placeholder row is shown to indicate zero spill activity.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/top_N_spilling_queries",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}