{
 "title": "WHPG Segment Details",
 "tags": [ "WHPG" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DataSourcePrometheus", "label": "DataSourcePrometheus", "query": "prometheus" },
   {
    "name": "DataSourceInfinity",
    "label": "DataSourceInfinity",
    "query": "yesoreyeram-infinity-datasource"
   },
   { "name": "DataSourceLoki", "label": "DataSourceLoki", "query": "loki" },
   {
    "name": "HostMountPoints",
    "label": "HostMountPoints",
    "query": {
     "query": "label_values(warehousepg_observability_node_filesystem_free_bytes,mountpoint)"
    }
   },
   {
    "name": "HostList",
    "label": "HostList",
    "query": {
     "query": "label_values(warehousepg_observability_node_filesystem_free_bytes,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Segment Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Segment Status",
     "type": "stat",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "warehousepg_observability_clinfo_total_primary_count",
       "legendFormat": "Total Primary Segments"
      },
      {
       "expr": "warehousepg_observability_clinfo_total_primary_count - warehousepg_observability_clinfo_curr_primary_down_count",
       "legendFormat": "Primary Segments Up"
      },
      {
       "expr": "warehousepg_observability_clinfo_curr_primary_down_count",
       "legendFormat": "Primary Segments Down"
      },
      {
       "expr": "warehousepg_observability_clinfo_preff_primary_up_count",
       "legendFormat": "Preferred Primary UP"
      },
      {
       "expr": "warehousepg_observability_clinfo_primary_not_in_sync_count",
       "legendFormat": "Primary Not In Sync"
      },
      {
       "expr": "warehousepg_observability_clinfo_total_mirror_count",
       "legendFormat": "Total Mirror Segments"
      },
      {
       "expr": "warehousepg_observability_clinfo_curr_mirror_up_count",
       "legendFormat": "Mirror Segments Up"
      },
      {
       "expr": "warehousepg_observability_clinfo_curr_mirror_down_count",
       "legendFormat": "Mirror Segments Down"
      },
      {
       "expr": "warehousepg_observability_clinfo_promoted_mirror_count",
       "legendFormat": "Promoted Mirror"
      },
      {
       "expr": "warehousepg_observability_clinfo_mirror_not_in_sync_count",
       "legendFormat": "Mirror Not In Sync"
      }
     ]
    },
    {
     "title": "Segment Status Timeline",
     "type": "state-timeline",
     "gridPos": { "h": 11, "w": 16, "x": 6, "y": 1 },
     "targets": [
      {
       "expr": "warehousepg_observability_seg_status",
       "legendFormat": "{{gp_segment_desc}} ({{role}})"
      }
     ]
    },
    {
     "title": "Segment Status",
     "type": "stat",
     "gridPos": { "h": 5, "w": 22, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "warehousepg_observability_seg_status",
       "legendFormat": "{{gp_segment_desc}} ({{role}})"
      }
     ]
    },
    {
     "title": "Database Size",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "warehousepg_observability_db_size",
       "legendFormat": "{{datname}}"
      }
     ]
    }
   ]
  },
  { "title": "System Load Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "System Load 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "warehousepg_observability_node_load1",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Load 5",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "warehousepg_observability_node_load5",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Load 15",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "warehousepg_observability_node_load15",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilisation for every Host (Current)",
     "type": "stat",
     "description": "Shows the percentage of CPU actively used on each host, calculated as 100 - %idle over the last 5 minutes. ",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (\n  avg by (instance) (\n    rate(warehousepg_observability_node_cpu_seconds_total{mode=\"idle\"}[5m])\n  ) * 100\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU Utilization per Host (15-min Avg)",
     "type": "timeseries",
     "description": "Shows the percentage of CPU currently in use per instance, calculated as 100 - %idle over the last 15 minutes. This provides a 15-minute rolling average of CPU utilization across the system.",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (\n  avg by (instance) (\n    rate(warehousepg_observability_node_cpu_seconds_total{mode=\"idle\"}[15m])\n  ) * 100\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Write Utilization (%)",
     "type": "timeseries",
     "description": "This panel shows the percentage of time the disk spent doing write operations averagedover the last 5 minutes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance) (\n  rate(warehousepg_observability_node_disk_write_time_seconds_total[5m]) * 100\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Read Utilization (%)",
     "type": "timeseries",
     "description": "This panel shows the percentage of time the disk spent doing read operations averaged over the last 5 minutes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance) (\n  rate(warehousepg_observability_node_disk_read_time_seconds_total[5m])*100\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "File System Device Error",
     "type": "timeseries",
     "description": "This panel shows total number of filesystem or device errors across all monitored disks and partitions for each server",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "sum(warehousepg_observability_node_filesystem_device_error) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Current Disk I/O for each host",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "targets": [
      {
       "expr": "sum by (instance) (warehousepg_observability_node_disk_io_now)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Free Disk Space(Host View) For Mount Point  - $HostMountPoints ",
     "type": "table",
     "description": "Shows the amount of free disk space available on the specified mount points for each host instance. This metric helps monitor storage capacity and detect low-disk conditions that may impact database performance or availability.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "warehousepg_observability_node_filesystem_free_bytes{instance=~\".+\", mountpoint=~\"$HostMountPoints\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Free Disk Space (Device View) for Host - $HostList",
     "type": "table",
     "description": "Shows the amount of free disk space available on all filesystem devices for the selected host instance. This metric helps track storage usage and identify when a host is running low on available disk space, which can affect database performance, logging, and overall system stability.",
     "gridPos": { "h": 8, "w": 11, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "warehousepg_observability_node_filesystem_free_bytes{instance=~\"$HostList\", device=~\".+\"}",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Swap Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available Swap Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (instance) (warehousepg_observability_node_memory_SwapFree_bytes)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Used Swap Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (instance) (warehousepg_observability_node_memory_SwapTotal_bytes-warehousepg_observability_node_memory_SwapFree_bytes)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Spill Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spill File Usage per Segment",
     "type": "table",
     "description": "Displays the total number of workfile spill files and total spill size (in bytes) for each segment in the cluster. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "parser": "backend",
       "source": "url",
       "type": "json",
       "url": "/spill_count_per_primary_seg",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "Top Queries by Spill Usage",
     "type": "table",
     "description": "Shows the top 20 queries generating workfile spills in the cluster.  If no active spill queries exist, a placeholder row is shown to indicate zero spill activity.",
     "gridPos": { "h": 8, "w": 11, "x": 12, "y": 55 },
     "targets": [
      {
       "parser": "backend",
       "source": "url",
       "type": "json",
       "url": "/top_N_spilling_queries",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    }
   ]
  }
 ]
}