{
 "title": "WHPG Query Details",
 "tags": [ "WHPG" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DataSourcePrometheus", "label": "DataSourcePrometheus", "query": "prometheus" },
   {
    "name": "DataSourceInfinity",
    "label": "DataSourceInfinity",
    "query": "yesoreyeram-infinity-datasource"
   },
   { "name": "DataSourceLoki", "label": "DataSourceLoki", "query": "loki" },
   {
    "name": "HostList",
    "label": "HostList",
    "query": {
     "query": "label_values(warehousepg_observability_node_filesystem_free_bytes,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Running Queries",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/current_running_queries",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Long Running  Queries",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/long_running_queries",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Blocked Queries",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/block_queries",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "title": "Query Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "warehousepg_observability_q_total",
     "legendFormat": "Total Queries"
    },
    {
     "expr": "warehousepg_observability_q_active",
     "legendFormat": "Active Queries"
    },
    {
     "expr": "warehousepg_observability_q_idle",
     "legendFormat": "Idle Queries"
    },
    {
     "expr": "warehousepg_observability_q_long_running_120s",
     "legendFormat": "Long Running Queries(>120s)"
    },
    {
     "expr": "warehousepg_observability_q_in_wait",
     "legendFormat": "Queries in Wait"
    },
    {
     "expr": "warehousepg_observability_q_blocked",
     "legendFormat": "Blocked Queries"
    }
   ]
  },
  {
   "title": "Connections Per User",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "warehousepg_observability_qu", "legendFormat": "{{username}}" }
   ]
  },
  {
   "title": "Queries per user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "warehousepg_observability_qu", "legendFormat": "{{username}}" }
   ]
  },
  {
   "title": "Queries Overview",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "warehousepg_observability_q_active",
     "legendFormat": "Active queries"
    },
    {
     "expr": "warehousepg_observability_q_idle",
     "legendFormat": "Idle queries"
    }
   ]
  },
  {
   "title": "Longest Running Query",
   "type": "table",
   "description": "This table shows list of queries running more than 120 seconds.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/pg_stat_activity",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Query Per Second (5 min rate)",
   "type": "timeseries",
   "description": "Measures the average number of queries executed per second over the last 5 minutes.\nThis metric is calculated using a monotonically increasing counter on total transactions(commit+rollback). A higher value indicates increased workload on the cluster. ",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "rate(warehousepg_observability_txn_total_queries_executed[5m])",
     "legendFormat": "QPS (5m rate)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Shows the current number of queries executed per second, calculated as the 1-minute rate of total transactions (commits + rollbacks). ",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(warehousepg_observability_txn_total_queries_executed[1m])",
     "legendFormat": "QPS (1 min rate)"
    }
   ]
  }
 ]
}